version: '3'
services:
  db:
    container_name: db
    image: mongo
    ports:
      - "27017:27017"
  node:
    container_name: node
    image: progettonest
    ports:
      - '3000:3000'
    depends_on:
      - db